
export EC2_HOME=/Users/ajmarsh/ec2-api-tools
export PATH=$PATH:$EC2_HOME/bin
export EC2_PRIVATE_KEY=/Users/ajmarsh/olarkSecret/pk-WGOZWJT7ZQ6D2GPF5WFEMI5EMZYBYMYE.pem
export EC2_CERT=/Users/ajmarsh/olarkSecret/cert-WGOZWJT7ZQ6D2GPF5WFEMI5EMZYBYMYE.pem
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home/
